### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Sandra631#1]
[infografia_gestion de proyectos.pdf](https://github.com/user-attachments/files/16756759/infografia_gestion.de.proyectos.pdf)

**Comment by Julissamigdalia** [comment]
Bien hecho
Calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
